### ISSUE TITLE
How can I get a list with items previously selected? 

### ISSUE THREAD

**Issue by mmurua98** [fabiomrosa/list-picker-js#1]
I'm using two lists, so when I submit the first one another list will appear. My question is when I want to return to my first list, how can I get the items I've already selected?

**Comment by fabiomrosa** [comment]
Hi @mmurua98,

This project is very outdated and on top of that I did this just for the sake of knowledge. That said, I strongly recommend that you don't use it in production or if you're planning to do that, try cloning the project and modifying the following file [dist](https://github.com/fabiomrosa/list-picker-js/tree/master/dist)/list-picker.js. To help you a little bit to understand how to use it, I "unminified" both main.js and style.css in the demo folder.

**Comment by mmurua98** [comment]
Thanks!
